### ISSUE TITLE
(stretch goal) Make the creating and scaling of runner resource immutable

### ISSUE THREAD

**Issue by myles-coleman** [engaging-finches/hello-k8s#32]

**Comment by meher-liatrio** [comment]
I don't know that we will get to scaling, but create/apply is immutable in that if you run `kubectl apply -f CR.yaml` multiple times without making any changes to the manifest, no changes should be made.

**Comment by meher-liatrio** [comment]
wont fix and close?

**Comment by myles-coleman** [comment]
> wont fix and close?

yeah sounds good
